GET http://localhost:3003/api/blogs

###
GET http://localhost:3003/api/users

###
POST http://localhost:3003/api/users
Content-Type: application/json

{
  "username": "root",
  "password": "sekret",
  "name": "Bob"
}

###
POST http://localhost:3003/api/login
Content-Type: application/json

{
  "username": "root",
  "password": "sekret"
}

###
POST http://localhost:3003/api/login
Content-Type: application/json

{
  "username": "root",
  "password": "password"
}

###
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjY3ZmM2ZTgzZmM0YzU0MzBjYzA5YzRiZiIsImlhdCI6MTc0NDU5NzYwMH0.2AAMd_PhVCtT3ebWS89o6gzlZlUAKJT8QkRpynmwSww

{
  "title": "My first blog post",
  "author": "Me",
  "url": "https://google.com",
  "likes": 151
}

###
DELETE http://localhost:3003/api/blogs/67fc72a75a0f53ee1bb2dc81