GET https://phonebook-still-field-9277.fly.dev/api/persons

###
GET http://localhost:3001/api/persons

###
GET http://localhost:3001/api/persons/67f2c4929e1b26f194b06ba6


###
POST https://phonebook-still-field-9277.fly.dev/api/persons HTTP/1.1
content-type: application/json

{
    "name": "Jane Doe",
    "number": "867-5309"
}

###
POST https://phonebook-still-field-9277.fly.dev/api/persons HTTP/1.1
content-type: application/json

{}

###
POST https://phonebook-still-field-9277.fly.dev/api/persons HTTP/1.1
content-type: application/json

{
    "number": "123-4567"
}

###
POST https://phonebook-still-field-9277.fly.dev/api/persons HTTP/1.1
content-type: application/json

{
    "name": "Bad name",
    "phone": "123456"
}

###
POST https://phonebook-still-field-9277.fly.dev/api/persons HTTP/1.1
content-type: application/json

{
  "name": "Ada Lovelace",
  "number": "1"
}