GET https://phonebook-still-field-9277.fly.dev/api/persons

###
DELETE https://phonebook-still-field-9277.fly.dev/api/persons/1451526820876033

###
DELETE http://localhost:3001/api/persons/67f2c4929e1b26f194b06ba6